import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import CartProvider from "./components/Providers";
import ShoppingCartModal from "./components/ShoppingCartModal";
import Head from "next/head";

const font = Lexend({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Boba Girls",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/app/icon.png" />
      </Head>
      <body className={font.className}>
        <CartProvider>
          <Navbar />
          {children}
          <ShoppingCartModal />
        </CartProvider>
      </body>
    </html>
  );
}
